version: '2.2'

services:
  taxi-api:
    image: taxi-api:latest
    ports:
      - 8080:8080
    environment:
      - PG_DATABASE=taxidatabase
      - PG_HOST=pgdb
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASS=postgres
    depends_on:
      - postgres

  postgres:
    container_name: pgdb
    image: postgres:9.6-alpine
    restart: always
    volumes:
      - ./pg:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_ROOT_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
